config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  get 'home/about' => 'homes#about'
  resources :books, except: [:new]
  resources :users, only: [:index, :edit, :show, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    #user-info
    @user = User.find(current_user.id)
    #new-book
    @book = Book.new
    #books
    @books = Book.all
  end

  def create
    #user-info
    @user = User.find(current_user.id)
    #books
    @books = Book.all
    #new-book
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

  def show
    #book-detail
    @bookd = Book.find(params[:id])
    #user-info
    @user = User.find(@bookd.user_id)
    #new-book
    @book = Book.new
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end


  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_side.html.erb
 <!--左側user-infoここから-->
    <h3>User info</h3>
    <%= form_with model:user, local:true do |f| %>
    <table class="table my-3">
      <tr class="m-2">
        <th><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %></th>
        <th></th>
      </tr>
      <tr class="m-2">
        <td>name</td>
        <td><%= user.name %></td>
      </tr>
      <tr class="m-2">
        <td>introduction</td>
        <td><%= user.introduction %></td>
      </tr>
    </table>
    <%= link_to edit_user_path(user.id), class:"btn btn-outline-secondary btn-block mb-5" do %><i class="fas fa-user-cog"></i><% end %>
    <% end %>

    <!--左側new-bookここから-->
    <h3>New book</h3>
    <%= form_with model: book, local:true do |f| %>
    <div class="form-group">
      <label>Title</label><br>
      <%= f.text_field :title, class:"form-control" %>
    </div>
    <div class="form-group">
      <label>Opinion</label><br>
      <%= f.text_area :body, class:"form-control" %>
    </div>
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    <% end %>

app/views/books/edit.html.erb
<div class="container">

  <p class="text-danger">
    <% if @book.errors.any? %>
      <%= @book.errors.count %> error prohibited this obj from being saved:<br>
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </p>

  <div class="row">

    <div class="col">

      <h2>Editing Book</h2>
      <%= form_with model:@book, local:true do |f| %>
      <div class="field mb-3">
        <label>Title</label><br>
        <%= f.text_field :title, autofocus: true %>
      </div>
      <div class="field mb-3">
        <label>Opinion</label><br>
        <%= f.text_area :body, autofocus: true %>
      </div>
      <%= f.submit 'Update Book', class:"btn btn-success mb-3" %>
      <% end %>

      <%= link_to 'Show', book_path %> |
      <%= link_to 'Back', books_path %>

    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">

  <p class="text-danger">
    <% if @book.errors.any? %>
      <%= @book.errors.count %> error prohibited this obj from being saved:<br>
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
  </p>

  <div class="row">

    <div class="col-md-3">
    <!--部分テンプレートの呼び出し-->
    <%= render 'books/side', user: @user, book: @book %>
    </div>

    <!--右側booksここから-->
    <div class="col-md-8 offset-md-1">
      <h3>Books</h3>
      <table class="table table-hover">
        <thead>
          <tr>
            <th></th>
            <th>title</th>
            <th>opinion</th>
          </tr>
        </thead>
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <th><%= link_to attachment_image_tag(book.user, :profile_image, format: 'jpeg', fallback: "no_image.jpg", size: "40x40"), user_path(book.user_id) %></th>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-3">
    <!--部分テンプレートの呼び出し-->
    <%= render 'books/side', user: @user, book: @book %>
    </div>

    <!--右側book-detailここから-->
    <div class="col-md-8 offset-md-1">
      <h3>Book detail</h3>
      <table class="table">
        <tr>
          <td>
            <%= link_to user_path(@bookd.user_id) do %><%= attachment_image_tag @bookd.user, :profile_image, fallback: "no_image.jpg", size: "40x40" %><br>
            <label><%= @bookd.user.name %></label>
            <% end %>
          </td>
          <td><%= link_to @bookd.title, book_path(@bookd.id) %></td>
          <td><%= @bookd.body %></td>
          <% if @bookd.user_id == current_user.id %>
          <td><%= link_to 'Edit', edit_book_path(@bookd.id), class:"btn btn-success" %></td>
          <td><%= link_to 'Destroy', book_path(@bookd.id), method: :delete, class:"btn btn-danger", "data-confirm" => "Are you sure to delete this book?" %></td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>