config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions'}
  get 'home/about' => 'homes#about'
  resources :books, except: [:new]
  resources :users, only: [:index, :edit, :show, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/2285947374.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="mb-3">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand p-1" href="/">Bookers</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav text-light">

            <% if user_signed_in? %>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' Home', user_path(current_user.id), class:"fas fa-home text-light" %>
            </li>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' Users', users_path, class:"fas fa-users text-light" %>
            </li>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' Books', books_path, class:"fas fa-book-open text-light" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to ' logout', destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt text-light" %>
            </li>
            <% else %>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' Home', root_path, class:"fas fa-home text-light" %>
            </li>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' About', home_about_path, class:"fas fa-link text-light" %>
            </li>
            <li class="nav-item mr-3 my-2">
              <%= link_to ' sign up', new_user_registration_path, class:"fas fa-user-plus text-light" %>
            </li>
            <li class="nav-item my-2">
              <%= link_to ' login', new_user_session_path, class:"fas fa-sign-in-alt text-light" %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header>

  <body>
    <!--フラッシュメッセージ-->
    <p class="text-success">
      <%= flash[:notice] %>
    </p>

    <%= yield %>
    <!--トグルを動かすために読み込む-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row d-flex justify-content-center">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </footer>
</html>